import { Router } from 'express';
import { signup } from '../handlers/user/signup';
import { login } from '../handlers/user/login';
import { getuser } from '../handlers/user/getUser';
import { updateuser } from '../handlers/user/updateUser';
import { deleteuser } from '../handlers/user/deleteUser';
import {signupMiddleware,loginMiddleware,getuserMiddleware,deleteMiddleware,errorhandel} from '../utils/middleware';
const userRouter = Router();
userRouter.post("/signup",signupMiddleware,errorhandel,signup);
userRouter.post("/login",loginMiddleware,errorhandel,login);
userRouter.get("/getuser",getuserMiddleware,errorhandel, getuser);
userRouter.put("/updateuser",signupMiddleware,errorhandel, updateuser);
userRouter.delete("/deleteuser",deleteMiddleware,errorhandel, deleteuser);
export default userRouter;