import { Router } from 'express';
import { signup } from '../handlers/user/signup';
import { login } from '../handlers/user/login';
import { getuser } from '../handlers/user/getUser';
import { updateuser } from '../handlers/user/updateUser';
import { deleteuser } from '../handlers/user/deleteUser';
const userRouter = Router();
userRouter.post("/signup", signup);
userRouter.post("/login", login);
userRouter.get("/getuser", getuser);
userRouter.put("/updateuser", updateuser);
userRouter.delete("/deleteuser", deleteuser);
export default userRouter;